version: '{build}'
skip_tags: false
clone_depth: 1
test: off

branches:
  only:
  - master

build_script:
- cmd: make.cmd

artifacts:
  - path: 'output\*.*'
    name: packages
  - path: 'reports'
    name: reports

deploy:
  provider: NuGet
  api_key:
    secure: wsVSfiTOvjdQgExU1aVzfww+N1ptKt1et5epn7/mx/67+FI/QxR76eR7oGmEDNr+
  skip_symbols: false
  on:
    branch: master
    appveyor_repo_tag: true